export const allCourse = {
  results: [
    {
      _class: "course",
      id: 1362070,
      title: "React - The Complete Guide 2024 (incl. Next.js, Redux)",
      url: "/course/react-the-complete-guide-incl-redux/",
      is_paid: true,
      price: "₹3,999",
      price_detail: {
        amount: 3999,
        currency: "INR",
        price_string: "₹3,999",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "5-jz7WrvRQqPcBv0l1mJbw",
      visible_instructors: [
        {
          _class: "user",
          title: "Academind by Maximilian Schwarzmüller",
          name: "Academind by Maximilian",
          display_name: "Academind by Maximilian Schwarzmüller",
          job_title: "Online Education",
          image_50x50:
            "https://img-b.udemycdn.com/user/50x50/31926668_94e7_6.jpg",
          image_100x100:
            "https://img-b.udemycdn.com/user/100x100/31926668_94e7_6.jpg",
          initials: "AS",
          url: "/user/academind/",
        },
        {
          _class: "user",
          title: "Maximilian Schwarzmüller",
          name: "Maximilian",
          display_name: "Maximilian Schwarzmüller",
          job_title: "AWS certified, Professional Web Developer and Instructor",
          image_50x50:
            "https://img-b.udemycdn.com/user/50x50/13952972_e853.jpg",
          image_100x100:
            "https://img-b.udemycdn.com/user/100x100/13952972_e853.jpg",
          initials: "MS",
          url: "/user/maximilian-schwarzmuller/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/1362070_b9a1_2.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/1362070_b9a1_2.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/1362070_b9a1_2.jpg",
      published_title: "react-the-complete-guide-incl-redux",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Dive in and learn React.js from scratch! Learn React, Hooks, Redux, React Router, Next.js, Best Practices and way more!",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 4471614,
      title: "The Ultimate React Course 2024: React, Next.js, Redux & More",
      url: "/course/the-ultimate-react-course/",
      is_paid: true,
      price: "₹799",
      price_detail: {
        amount: 799,
        currency: "INR",
        price_string: "₹799",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "lNbDnLoSR2K13SXb8fgwCg",
      visible_instructors: [
        {
          _class: "user",
          title: "Jonas Schmedtmann",
          name: "Jonas",
          display_name: "Jonas Schmedtmann",
          job_title: "Web Developer, Designer, and Teacher",
          image_50x50:
            "https://img-b.udemycdn.com/user/50x50/7799204_2091_5.jpg",
          image_100x100:
            "https://img-b.udemycdn.com/user/100x100/7799204_2091_5.jpg",
          initials: "JS",
          url: "/user/jonasschmedtmann/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/4471614_361e_8.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/4471614_361e_8.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/4471614_361e_8.jpg",
      published_title: "the-ultimate-react-course",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Master modern React from beginner to advanced! Next.js, Context API, React Query, Redux, Tailwind, advanced patterns",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 4498186,
      title: "Figma to React : Build 10 Login Pages in React 2022",
      url: "/course/figma-to-react-build-10-login-pages-in-react-2022/",
      is_paid: true,
      price: "₹1,799",
      price_detail: {
        amount: 1799,
        currency: "INR",
        price_string: "₹1,799",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "H3duI4EYTf6tvm8JEB36Ow",
      visible_instructors: [
        {
          _class: "user",
          id: 121760435,
          title: "K.Sathyaprakash Reddy",
          name: "K.Sathyaprakash",
          display_name: "K.Sathyaprakash Reddy",
          job_title: "Full Stack Developer",
          image_50x50:
            "https://img-c.udemycdn.com/user/50x50/121760435_f52a_7.jpg",
          image_100x100:
            "https://img-c.udemycdn.com/user/100x100/121760435_f52a_7.jpg",
          initials: "KR",
          url: "/user/ksathyaprakash-reddy/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/4498186_8cac_2.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/4498186_8cac_2.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/4498186_8cac_2.jpg",
      published_title: "figma-to-react-build-10-login-pages-in-react-2022",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline: "Build 10 Login pages in React with Figma Prototypes",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 1565838,
      title: "The Complete 2024 Web Development Bootcamp",
      url: "/course/the-complete-web-development-bootcamp/",
      is_paid: true,
      price: "₹3,099",
      price_detail: {
        amount: 3099,
        currency: "INR",
        price_string: "₹3,099",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "snw1d5jtQW25JtICUjtHyA",
      visible_instructors: [
        {
          _class: "user",
          title: "Dr. Angela Yu, Developer and Lead Instructor",
          name: "Dr. Angela",
          display_name: "Dr. Angela Yu, Developer and Lead Instructor",
          job_title: "Developer and Lead Instructor",
          image_50x50:
            "https://img-b.udemycdn.com/user/50x50/31334738_a13c_3.jpg",
          image_100x100:
            "https://img-b.udemycdn.com/user/100x100/31334738_a13c_3.jpg",
          initials: "DY",
          url: "/user/4b4368a3-b5c8-4529-aa65-2056ec31f37e/",
        },
      ],
      image_125_H:
        "https://img-c.udemycdn.com/course/125_H/1565838_e54e_18.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/1565838_e54e_18.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/1565838_e54e_18.jpg",
      published_title: "the-complete-web-development-bootcamp",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, PostgreSQL, Web3 and DApps",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 6035102,
      title: "Complete web development course",
      url: "/course/web-dev-master/",
      is_paid: true,
      price: "₹1,999",
      price_detail: {
        amount: 1999,
        currency: "INR",
        price_string: "₹1,999",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "YVRRCEmMQ0-EFzauWLoEFQ",
      visible_instructors: [
        {
          _class: "user",
          id: 272686492,
          title: "Hitesh Choudhary",
          name: "Hitesh",
          display_name: "Hitesh Choudhary",
          job_title: "A teacher who loves to teach about Technology",
          image_50x50:
            "https://img-c.udemycdn.com/user/50x50/272686492_6b9b.jpg",
          image_100x100:
            "https://img-c.udemycdn.com/user/100x100/272686492_6b9b.jpg",
          initials: "HC",
          url: "/user/hitesh-choudharycom/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/6035102_7d1a.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/6035102_7d1a.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/6035102_7d1a.jpg",
      published_title: "web-dev-master",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Only web development course that you will need. Covers HTML, CSS, Tailwind, Node, React, MongoDB, Prisma, Deployment etc",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 5136972,
      title: "React Native, Redux & Express - Full Stack React Native",
      url: "/course/mern-stack-react-native-redux/",
      is_paid: true,
      price: "₹799",
      price_detail: {
        amount: 799,
        currency: "INR",
        price_string: "₹799",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "aeCC-qiSRIyoppq1YRZP-Q",
      visible_instructors: [
        {
          _class: "user",
          id: 185527748,
          title: "Niraj Dhungana",
          name: "Niraj",
          display_name: "Niraj Dhungana",
          job_title: "Developer and Online Instructor",
          image_50x50:
            "https://img-c.udemycdn.com/user/50x50/185527748_a07a.jpg",
          image_100x100:
            "https://img-c.udemycdn.com/user/100x100/185527748_a07a.jpg",
          initials: "ND",
          url: "/user/niraj-dhungana-92/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/5136972_dbb6.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/5136972_dbb6.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/5136972_dbb6.jpg",
      published_title: "mern-stack-react-native-redux",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Learn to build full-stack apps with MERN: React Native, Redux for front-end and Node, Express, MongoDB for backend.",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 625204,
      title: "The Web Developer Bootcamp 2024",
      url: "/course/the-web-developer-bootcamp/",
      is_paid: true,
      price: "₹3,499",
      price_detail: {
        amount: 3499,
        currency: "INR",
        price_string: "₹3,499",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "t9T8ufLHR2qcxfXeKWfLOA",
      visible_instructors: [
        {
          _class: "user",
          title: "Colt Steele",
          name: "Colt",
          display_name: "Colt Steele",
          job_title: "Developer and Bootcamp Instructor",
          image_50x50:
            "https://img-b.udemycdn.com/user/50x50/4466306_6fd8_3.jpg",
          image_100x100:
            "https://img-b.udemycdn.com/user/100x100/4466306_6fd8_3.jpg",
          initials: "CS",
          url: "/user/coltsteele/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/625204_436a_3.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/625204_436a_3.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/625204_436a_3.jpg",
      published_title: "the-web-developer-bootcamp",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "10 Hours of React just added. Become a Developer With ONE course - HTML, CSS, JavaScript, React, Node, MongoDB and More!",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 705264,
      title: "Modern React with Redux [2024 Update]",
      url: "/course/react-redux/",
      is_paid: true,
      price: "₹3,999",
      price_detail: {
        amount: 3999,
        currency: "INR",
        price_string: "₹3,999",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "Z00oTrsURV-PcyE1ChLh5A",
      visible_instructors: [
        {
          _class: "user",
          title: "Stephen Grider",
          name: "Stephen",
          display_name: "Stephen Grider",
          job_title: "Engineering Architect",
          image_50x50: "https://img-b.udemycdn.com/user/50x50/5487312_0554.jpg",
          image_100x100:
            "https://img-b.udemycdn.com/user/100x100/5487312_0554.jpg",
          initials: "SG",
          url: "/user/sgslo/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/705264_caa9_13.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/705264_caa9_13.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/705264_caa9_13.jpg",
      published_title: "react-redux",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Master React and Redux. Apply modern design patterns to build apps with React Router, TailwindCSS, Context, and Hooks!",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 1436092,
      title: "React Native - The Practical Guide [2024]",
      url: "/course/react-native-the-practical-guide/",
      is_paid: true,
      price: "₹4,999",
      price_detail: {
        amount: 4999,
        currency: "INR",
        price_string: "₹4,999",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "k3kX4Us5QXm7hxCEoeC5mg",
      visible_instructors: [
        {
          _class: "user",
          id: 31926668,
          title: "Academind by Maximilian Schwarzmüller",
          name: "Academind by Maximilian",
          display_name: "Academind by Maximilian Schwarzmüller",
          job_title: "Online Education",
          image_50x50:
            "https://img-c.udemycdn.com/user/50x50/31926668_94e7_6.jpg",
          image_100x100:
            "https://img-c.udemycdn.com/user/100x100/31926668_94e7_6.jpg",
          initials: "AS",
          url: "/user/academind/",
        },
        {
          _class: "user",
          id: 13952972,
          title: "Maximilian Schwarzmüller",
          name: "Maximilian",
          display_name: "Maximilian Schwarzmüller",
          job_title: "AWS certified, Professional Web Developer and Instructor",
          image_50x50:
            "https://img-c.udemycdn.com/user/50x50/13952972_e853.jpg",
          image_100x100:
            "https://img-c.udemycdn.com/user/100x100/13952972_e853.jpg",
          initials: "MS",
          url: "/user/maximilian-schwarzmuller/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/1436092_2024_4.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/1436092_2024_4.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/1436092_2024_4.jpg",
      published_title: "react-native-the-practical-guide",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Use React Native and your React knowledge to build native iOS and Android Apps - incl. Push Notifications, Hooks, Redux",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 3873464,
      title: "Next.js 15 & React - The Complete Guide",
      url: "/course/nextjs-react-the-complete-guide/",
      is_paid: true,
      price: "₹4,999",
      price_detail: {
        amount: 4999,
        currency: "INR",
        price_string: "₹4,999",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "A9qEHGzqS-2KwOtKj_uxmw",
      visible_instructors: [
        {
          _class: "user",
          id: 13952972,
          title: "Maximilian Schwarzmüller",
          name: "Maximilian",
          display_name: "Maximilian Schwarzmüller",
          job_title: "AWS certified, Professional Web Developer and Instructor",
          image_50x50:
            "https://img-c.udemycdn.com/user/50x50/13952972_e853.jpg",
          image_100x100:
            "https://img-c.udemycdn.com/user/100x100/13952972_e853.jpg",
          initials: "MS",
          url: "/user/maximilian-schwarzmuller/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/3873464_403c_3.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/3873464_403c_3.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/3873464_403c_3.jpg",
      published_title: "nextjs-react-the-complete-guide",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Learn NextJS 15 from the ground up and build fullstack ReactJS + NextJS apps with the App Router or Pages Router!",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 1552218,
      title: "Master Elementor in 1 hour - The #1 WordPress Page Builder",
      url: "/course/master-elementor-in-1-hour/",
      is_paid: true,
      price: "₹3,499",
      price_detail: {
        amount: 3499,
        currency: "INR",
        price_string: "₹3,499",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "k1h5n2-TSrW_Pr4eJsFHZA",
      visible_instructors: [
        {
          _class: "user",
          id: 26183392,
          title: "Divit Mehta",
          name: "Divit",
          display_name: "Divit Mehta",
          job_title: "Entrepreneur, Teacher and Content Creator.",
          image_50x50:
            "https://img-c.udemycdn.com/user/50x50/26183392_d586_4.jpg",
          image_100x100:
            "https://img-c.udemycdn.com/user/100x100/26183392_d586_4.jpg",
          initials: "DM",
          url: "/user/divit-mehta/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/1552218_85ac.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/1552218_85ac.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/1552218_85ac.jpg",
      published_title: "master-elementor-in-1-hour",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Elementor for Beginners: Create WordPress websites using Elementor. No WordPress or Elementor Experience Required!",
      instructor_name: null,
    },
    {
      _class: "course",
      id: 2626524,
      title: "Level 1 CFA® Exam Prep Bootcamp (Part 1/2)",
      url: "/course/level-1-cfa-exam-prep-bootcamp/",
      is_paid: true,
      price: "₹3,099",
      price_detail: {
        amount: 3099,
        currency: "INR",
        price_string: "₹3,099",
        currency_symbol: "₹",
      },
      price_serve_tracking_id: "PTWqAYNgS76fdQkcBRT2qw",
      visible_instructors: [
        {
          _class: "user",
          id: 8280056,
          title: "365 Careers",
          name: "365",
          display_name: "365 Careers",
          job_title:
            "Creating opportunities for Data Science and Finance students",
          image_50x50:
            "https://img-c.udemycdn.com/user/50x50/8280056_7887_3.jpg",
          image_100x100:
            "https://img-c.udemycdn.com/user/100x100/8280056_7887_3.jpg",
          initials: "3C",
          url: "/user/365careers/",
        },
        {
          _class: "user",
          id: 77357702,
          title: "Ivan Kitov, CFA",
          name: "Ivan",
          display_name: "Ivan Kitov, CFA",
          job_title: "Finance",
          image_50x50:
            "https://img-c.udemycdn.com/user/50x50/77357702_e9f7_3.jpg",
          image_100x100:
            "https://img-c.udemycdn.com/user/100x100/77357702_e9f7_3.jpg",
          initials: "IK",
          url: "/user/ivan-angelov-kitov/",
        },
      ],
      image_125_H: "https://img-c.udemycdn.com/course/125_H/2626524_f8a6_4.jpg",
      image_240x135:
        "https://img-c.udemycdn.com/course/240x135/2626524_f8a6_4.jpg",
      is_practice_test_course: false,
      image_480x270:
        "https://img-c.udemycdn.com/course/480x270/2626524_f8a6_4.jpg",
      published_title: "level-1-cfa-exam-prep-bootcamp",
      tracking_id: "",
      locale: {
        _class: "locale",
        locale: "en_US",
        title: "English (US)",
        english_title: "English (US)",
        simple_english_title: "English",
      },
      predictive_score: null,
      relevancy_score: null,
      input_features: null,
      lecture_search_result: null,
      curriculum_lectures: [],
      order_in_results: null,
      curriculum_items: [],
      headline:
        "Level 1 CFA® Bootcamp: Ethics, Quantiative Methods, Corporate Finance, Economics, and Alternative Investments",
      instructor_name: null,
    },
  ],
};
